export interface contabilidad {
    idCon?: number,
    Concepto: string,
    fecha: any,
    tipo: number,
    idcate:number,
    monto: number,
    iduser: number,
    nombre: string,
    activo: number,
    status: number,
    adelanto: number,
    restante: number,
    suma:number,
    idscu:any,
    idsuc:any,
}